<?php
$names = array(
    "Electricpicnic" => "Electric Picnic",
    "Forbiddenfruit" => "Forbidden Fruit",
    "Trinityball" => "Trinity Ball"
);

$noimages = array("latitude14", "electricpicnic14");

$festivals = array(
"forbiddenfruit14" => array(
    1 => array(
        "Flaming Lips" => "PLPW9eE32IrZ3ND-vUAY8
        2ffiFRdDeU0NB",
        "Bell X1" => "PL95VMtu-U8XxUgc6fB5kX1dSm2VSZPxwh",
        "Flying Lotus" => "PLi3qgNShk0tubISUu9VbW4IJpQSHckCqu",
        "Fuck Buttons" => "PLc6ucmdGlNQo3lDcT1N1PsxRBYrAmpUHT",
        "Nils Frahm" => "PLLJyVqt3h2XEIJjudxkxDF1w5QI4ybuh1",
        //"Thundercat" => "",
        "Captain Murphy" => "PL2bU37o-CYslIHRaZOt_I4JSergFksXXU",
        "Young Knives" => "PLinWRcD76vJ0LPCtAR6UjbTcPursLw_Dv",
        "Kid Karate" => "",
        "To Kill A King" => "PLh_cq3Y_6Gpv_mxcsGlZ_RLrxWUZlxaLN",
        //"Vann Music" => "",
        "2ManyDJs" => "PL7DOEaVoSpnfoKNHrvajUdNUpL3TjSvV8",
        "Soulwax" => "PLC-gLM2BBhSMIaaqCNO1jliaqfrn4t-Y3",
        "Wild Beasts" => "PL4zThKHHkRUZl2dDicq3Gl159me1npZCp",
        "Warpaint" => "PLXdj4P-_tZNIp34OXta39A3CqNHZcvoKj",
        "T.E.E.D." => "PL6r6n69mILXKNPNPx9SKZRdAeKX0LEIg-",
        "Public Enemy" => "PLsm5XUxQMl307n-yD12GstC8xDMNqSsPQ",
        "Little Dragon" => "PLO_5Yl_UetFNdWRivanUgs5rc3PzO7a-l",
        "Gold Panda" => "PL8poiIplUu_Hqw05EKh7-HXlFxjoFMQz6",
        "Klangkarussell" => "PLg7t5XgZSven7YOkHAxY3SuaDWWpO0u-K")
        //"The Range" => "",
        //"Brian Deady" => "",
    ),
"latitude14" => array (
    1 => array(
        "Two Door Cinema Club" => "PLFSwPIw5qDue0QqF2ZpU9Uu7WoYdGD0VM",
        "Editors" => "PLYMaiFAPSI27boX2NHdETaj3r1VR2ue_6",
        "Crystal Fighters" => "PLyv6FZDnaws8DIDtT6OZJJYDRstc8jp4D",
        "Kelis" => "PLurxr-RzmraTFsRdmb-J2f-_zkekmS9_a",
        "Billy Bragg" => "PLLkdyA_QjtjWKiLHmgw8TnI7-IoLkKcQT",
        "Damon Albarn" => "PLgRCC8t3yXZqHoH-TbPS3OcwlKZKG33MS",
        "Bombay Bicycle Club" => "PLRoQLTxUh8caUuvnxH30ArXQALx12P3jY",
        "First Aid Kit" => "PLhp3j5K5Dotx74S2ZrY4Km0e-d07dpIPt",
        //"James" => "",
        "The Afghan Whigs" => "PLBpi9R93DAXqIYePZIrFdK_5Wfge_17D7",
        "Booker T. Jones" => "PLLgk2iVZrJ6LfRROPgg_4akHMZSObdOzF",
        "Tinariwen" => "PLJ4U_aKxtYF9BTARnzpup-1GRhRqE6ulo",
        "The Black Keys" => "PLS4H6sV00mHJOVUdNqlzehpXFpqBg5S0s",
        "Tame Impala" => "PLNrI2ORf4u-LyUU_bRYZDskElGBAToMQF",
        "HAIM" => "PLDgP-I_39kOYTaqvJHpWuJkRep3-nur1P",
        "Phosphorescent" => "PLu0ofbG4xSgoZozx2TjfyRpydCoFPcKVb",

        //BBC Radio 6 Music Stage
        "Asgeir Trausti" => "PL3Mi6sgHkvt-Ohd2pCgfrsHdKBGAHjiuZ",
        "Augustines" => "PLZsMwaYOudvoESWl0D9XR-CXPqUDJy0ea",
        "Mogwai" => "PL4Z-LDuzeu_BNKM6g3YR1MBhQp-IUOgZT",
        "Slowdive" => "PLdaR2kkwXcVDaQcfQ2lpM8itr57tNOewm",
        "Anna Calvi" => "PL9m4ntqe1M1IdU_SoEmzxT7Y_sISLD25Z",
        "Goat" => "PLxpiSSE5UuR43cvigTdWLKqXzcmnO2xQO",
        "Temples" => "PLQa84FNskTsBPfYAHadEQqUtt3SgVZVig",
        "SOHN" => "PLX4DbtuXEgAQdQcOAIHd92Qr8P8t8J3LR",
        //"Hozier" => "",
        "Royksopp and Robyn" => "PLHTZVNvApcMM-64Fj8Fzr0oPCx_rEuKU4",
        "James Vincent McMorrow" => "PLXaENCdnmEnaiNNYJL40d1g1Ohas9RS61",
        "Daryl Hall and John Oates" => "PLEBDA92B42BF01F42",
        "Jungle" => "PLg4dDTpUREiiB-70QKVnur_znn7F17MX0",
        "Conor Oberst" => "PLat6EiN60AUEbs0B6PWAgTd-RwghHGdoz",
        "Agnes Obel" => "PLL16kN8b1au75W3RkUCIYHQo-s-58DAol",
        "Damien Jurado" => "PLUUaq4jnSm_Xky09L_6ijCnGUAOkix5jY",
        "Lykke Li" => "PLMnSGPMM-RICm8whZVxnPbmqMOGgXXK2C",
        "Clean Bandit" => "PLKDbJAfbkojruTny6I_bPXiaCpGJhp0cD",
        "The War on Drugs" => "PLu84j_a_lJ5t5ysX-uNTca5vN6nTj-kgB",
        "Parquet Courts" => "PLBJ6p8xgfe4HdEY8upFVxPbJ4y3TGNOk-",
        "George Ezra" => "PLalGxzV0lSzC_Cru87azR3IO0fMmIWbA8",
        "Valerie June" => "PLiUzrQ2nIGCGncPeFG060q6f-Z0Aa1lN8",

        //The Lake Stage
        "Luke Sital-Singh" => "PLZnzO00MXv1cv7GeBE-4Xxo1rb5MxJBFc",
        "Chrissie Hynde" => "PL19ZHDt3AVhXhYpyqKfhHb-96c50FvYJj",
        "Paul Heaton & Jacqui Abbott" => "PLTyQT4uk2sb3SPRAmTtwLMGbMvSxHlOCf",
        "The Jayhawks" => "PLxL1MCUUH7Vf_pHmm1QKQ8OwkJi0BHGmA",
        "Bondax" => "PLKSww7hVUa1iJtclnXUs_x32vJyblp2dA",
        "Cate Le Bon" => "PLUKltnEQo4BAP2VWDogmOVEeJNd5hAQlm",
        "Catfish & The Bottlemen" => "PLyIMc0mlOVq5xfAl7rrysrCl2HkFIdqxh",
        "Childhood" => "PLzZ-_XmI9ZoxOcVyE-pKVRBYUXP3Mpcv6",
        "Circa Waves" => "PL5RC2GrNRZqpxGsOxfkG3McFMN7e2EWJZ",
        //"D.D Dumbo" => "",
        //"Elli Ingram" => "",
        //"Gengahr" => "",
        "Moko" => "PLDJ7fo-M-T_ebJirfSQK2RXg0okvOjtuW",
        //"Norma Jean Martine" => "",
        //"Oliver Wilde" => "",
        "Only Real" => "PLnp8C1cvqOFtcIo8bPkUBSAKfTXBh4d1W",
        //"Slaves" => "",
        "Soak" => "PLmTYQgsJAWrS1_2OPaK0sDzJ9B1EKLSY5",
        //"Spring King" => "",
        "Sumie" => "PLEK6BIninTiwA_tHcJdIUuys9tL4JNvPp",
        //"The Bohicas" => "",
        "Womans Hour" => "PLCIdWEv9jKlrTLINH1Mamg-U2xzdXKt50",
        //The i Arena
        "Cass McCombs" => "PLyZY14-OtyFbrHnRXKsfORriaJZ_8hYM8", 
        "Dawes" => "PLtFYhNx1SCQid5z1PsvdJkZ4-iJoSe__D", 
        "Eagulls" => "PLkEqFmygyebYy2u5qjy6at-fBkD_cDtkr", 
        "East India Youth" => "PL8LY58_S0dVsOUSexIsdI_lBoT8eHH2bj", 
        "Future Islands" => "PL6_mL3l364WasuyvdjODm1cSOO51i0L05", 
        "Hiss Golden Messenger" => "PLIm5ozCey4OJkjwlUvQbFudCiZq4TtA2q", 
        "James Holden" => "PLXIE3UBGrM6bvxrNhCOpBfUQyvf3JUqwk", 
        "John Wizards" => "PLcjoSd4cCwFz5zZBtG83kv9e-ZeoqyuYg", 
        "Josephine Foster" => "PLFkUbKLm8kUaECm9FlF9MuzX_Vaogo93-", 
        "Julia Holter" => "PLNnoJxnrdhQRyS5-6HvTIjfcQu-xx1KG4", 
        "Koreless" => "PL_co4HKWIH6G9HpBOb0nSFbhmFMRPKf9n", 
        //"Kwabs" => "", 
        "Marika Hackman" => "PL38w7Zsa3WvOOm8SL77HKQ838huP_XxxW", 
        "Mighty Oaks" => "PL9iTEH8DZYw3nJh7Q4s0KtECj8zC8LfFz", 
        "Mnek" => "PLtmxSb8Fuh9b69OGNpiYpOU7WjtEjZA9b", 
        "Nils Frahm" => "PLnIpeMrTPTzgeXdDb1EvT02U7iSoFViyS", 
        //"Rhodes" => "", 
        "Ry X" => "PLPq120kYdNWB8-48YmUo2Mtk69g4UZf-R", 
        "Son Lux" => "PL5xwACC2gLx96x_Wl1vcH_Nw_YbkXdYRg", 
        "Syd Arthur" => "PLb37R31zHQy1VOmaWXnwuD5ZcYj50RCiW", 
        //"Teen" => "", 
        //"The Acid" => "", 
        "Tom Vek" => "PLAhXf2HWbCkda0hAZmnpLzraRq-DrBAHR", 
        "Tycho" => "PLxMZrdvyR28Ctssnc3Lkn5LjmBj1S1G57", 
        //"Vaults" => "", 
        "Young Fathers" => "PLsq-xkHP19TekTPAXd7cbGDOUP4ooYqzD", 
        //The Alcove
        //"Ady Suleiman" => "", 
        "Danni Nicholls" => "PLXaL22hr3OvxwBfPz87hIkAlHlrowDSvW", 
        "Elliphant" => "PLKkZ32tpCQTk20lo3dz-TWCVstcOKm7J5", 
        //"Emilie Nicholas" => "", 
        //"Glass Animals" => "", 
        "Milky Chance" => "PLHcdpeJPEIt8kRFXPbJl79F3ZhSMaJEv1",
        "Solomon Grey" => "PL4UBx3-SkhBnwxtKcVWgkxuX-QI-KDHJa")
    ),
"life14" => array (
    1 => array(
        "Groove Armada" => "PLCIE83qzq3jfTgaLRVMrDl0Fro7k2oCN7", // Groove Armada
        "Four Tet" => "PLD8lj82m2VI4hs4kEsl8Oh41Qny59OMq5", //Four Tet
        "Jamie xx" => "PL3HjTCpqMAmaHNfnhUwPWGnH15LaIkDeI", //Jamie xx
        "LFO" => "PLyPL1Gj6K6FvL6ojktg_0CEc5U1NenvwS", //LFO
        "Maya Jane Coles" => "PLyVkUOER9bcRvo9jHWGDI1qR7_CnNt61_", //Maya Jane Coles
        "Joy Orbison" => "PLcPortpLsh4wEFhFu0IoAzcULKt1Xk8n-", //Joy Orbison
        "Karenn" => "PLiGdAOWEd8354wJfLYjdYaqxMjoNWy4uV", //Karenn
        "Hot Since 82" => "PLU-u92MgH_KDOYb5X4Ls2uqbL7fL9GCzQ", //Hot Since 82
        "Nina Kraviz" => "PLL_55RT74BG3x3UZejJ0XGbYEt5Tpj0bQ", //Nina Kraviz
        //"Dixon" => "", //Dixon
        "Ben Klock" => "PLKPvG7hZrLQXDj0bZxSmOjcKlR29pReNj", //Ben Klock
        "Dj Koze" => "PLiYvwFD3JZTVMPhzUY6pAuoI28AHX5OHC", //Dj Koze
        "Tensnake" => "PLUM0dTWRFYECPMclcedgPPJFXGIBgXeWO", //Tensnake
        "Rødhåd" => "ALYL4kY05133p7y_B_dO6NkZdBobuJVfcD", //Rødhåd SMALL
        "Nathan Fake" => "PLl-K4IA0akouTjybs8p3os-C3qtPapg2l", //Nathan Fake
        "Ben Pearce" => "PLQ-waTrG6Q5qwYc-CpVrwZQKHPkyiqfNW", //Ben Pearce
        "Dusky" => "PLL-9-Y0kG2K300ZMGijdGKin9SLyqNLmR", //Dusky
        "Mala SMALL" => "PLdvsPak9-11xittGr9gNZb65-ki5GOifU", //Mala SMALL
        "Waze & Odyssey" => "PLCEwyNqW8zyGcGiJyJy3iDcAG7Te7kbWq", //Waze & Odyssey SMALL
        "Intergalactic Gary" => "PLJYwhd0qpSzInRgQWta8X4Dmntxtv1a_L", //Intergalactic Gary SMALL
        //"Maurice Fulton" => "", //Maurice Fulton
        "Ejeca" => "PLecSsMzAxnowbTJHpgXICjEgeng5xVuGd", //Ejeca SMALL
        //"New Jackson" => "", //New Jackson
        //"Avalon" => "", //Avalon
        "Sensient" => "PLgn7wE93VLbRJIG2sdvQJ1lY4Eh4JbyeF", //Sensient
        "Kormac’s Big Band" => "PLgAWVxnf9wWQPHqQ0zhJpr-zdmfZRY4rX", //Kormac’s Big Band
        "EVP" => "PLaB3Y3PmC6rTXlmXsPtZoPInMunb2Lf79", //EVP
        "Parasense" => "PLWDwQK8f9bsUJ7p_mOY5pZ0xgi1_Frr3W", //Parasense
        "Egorythmia" => "PL3JkvO0sIqa3ypOuvFvw2SjilVX6WgzXU", //Egorythmia
        //"Sunil Sharpe SMALL" => "PLE8994569DC7843E1", //Sunil Sharpe SMALL
        //"Frank B" => "", //Frank B
        "Lumigraph" => "PLA_nhYCW8Xe2H4joHwldPcXjgnLdgSylQ", //Lumigraph SMALL
        //"Barry Redsetta" => "", //Barry Redsetta
        //"Nathan Jones" => "", //Nathan Jones
        //"Slowburn" => "", //Slowburn
        "Jonas Rathsman" => "PLG001TKsHzmkseW6Qe0Q4B7tPr215qcVm", //Jonas Rathsman
        "Danny Wang" => "PLL4e-PzjqLMxBRMGil3u7XKuMUT9WIQ1L", //Danny Wang
        "R.S.A.G." => "PLEvjUFqyYF49M3sy0xQIBLTqcPyze6Y72", //R.S.A.G.
        "S.P.Y." => "PLjaBPhNP-56qUUM0emEFq3gNWpwDjowx2", //S.P.Y.
        //"Raglans" => "", //Raglans
        //"Lasertom" => "", //Lasertom
        //"Hot Sprockets" => "", //Hot Sprockets
        "Commodo" => "PLcKf-SdjCMiScjug5frnoplTxEPwSZLoa", //Commodo
        //"Gantz" => "", //Gantz
        //"Dublin Afrobeat Ensemble" => "", //Dublin Afrobeat Ensemble
        "Sam Binga" => "PLw14iqk3SfpCdJ5EYq7sJrSdCGrgV0zsA", //Sam Binga
        "DJ Storm" => "PLFW16WayCdhn8crO6pM6fuGYXIgh57E4R", //DJ Storm
        //"Harry Wolfman" => "", //Harry Wolfman
        //"Real Connoisseur" => "", //Real Connoisseur
        //"UnknwN" => "", //UnknwN
        "Jacques Renault" => "PLEUN-iVwxxxmkqvv8pBnwHd-IPkES8WzU", //Jacques Renault
        "Mark Wells" => "PLklHV3NKRYQT150DSkqw32gvRKDwQ2HO9", //Mark Wells
        "TCTS" => "PLjFNX9g_NbAqJjl1FJ_VGkyhtbVU7W_e4", //TCTS
        "Lane 8" => "PLDgwZe2STF-ZmZ3GA1YEP-QyImSXvPXCb", //Lane 8
        //"Low Steppa" => "", //Low Steppa
        //"Meltybrains" => "", //Meltybrains
        //"Booka Brass Band" => "", //Booka Brass Band
        //"Morro 16" => "", //Morro 16
        //"Lunar Disko" => "", //Lunar Disko
        //"Apartment Records" => "", //Apartment Records
        "Animal Picnic" => "PLGeDXxvumORI46G9vBVPt-ZCR8mT_3kdb")
    ),
"trinityball14" => array(
    1 => array (
        "Example" => "PL7R0id_oPRp3anrlIXvd10TsAOm9A8QgB", // Topic Pop
        "Miles Kane" => "PL6coHCSJV2RmFLFajn3fDeEnV7vqKDvPG", // Topic Pop 
        "2ManyDJs" => "PL7DOEaVoSpnfoKNHrvajUdNUpL3TjSvV8", // Topic Pop
        "Soulwax" => "PLC-gLM2BBhSMIaaqCNO1jliaqfrn4t-Y3", // Topic Pop
        "Duke Dumont" => "PLVViFG9SxnScfAQB5s3e4XweCctIEopXe", // Topic Pop
        "Le Galaxie" => "PLBUg5er7n1-03BGrZI2Cjl591h651_rU3", // Topic Pop
        "Nina Nesbitt" => "PLIdewAGcqExVA-Wv4Ho-X-8BQtd2eEiWa", // Topic Pop
        "Original Rudeboys" => "PLMwOfsUbTjfsy19infQREybC2XA97noDJ", // Topic Pop
        "T.E.E.D." => "PL6r6n69mILXKNPNPx9SKZRdAeKX0LEIg-", // Topic Pop
        "Ben Pearce" => "PLQ-waTrG6Q5qwYc-CpVrwZQKHPkyiqfNW", // Topic Pop
        "Wilkinson" => "PLvxSrGioHAAX0ePkG_3AqNm96CdZRP9rj", // Topic Pop
        "Chlöe Howl" => "PLCEHGYymk2-MjaPn8-6IDcnwvRj9tVwjt", // Topic Pop
        "Laura Welsh" => "PL1kRMxZ099zLnma22Dp8JcMGc8sBcVK46", // Topic Pop
        "Saint Raymond" => "PLvdlgcVSkuIRj1p_AXpXkiH1d4ikUPinm", // User
        "Godfathers" => "PLXxBQeEQzEf4GdouGCuTMm0gkPLwEmwrl")
    ),
"electricpicnic14" => array(
    1 => array (
        "Portishead" => "PLbNPljg6lLxnBFDi-GliOI1W_4_TNnI4F", // Topic Pop
        "Outkast" => "PLazvjMpvktRuuoKZiYoqdjMqjqadxHJ4i", // Topic Pop
        "Beck " => "PLaQqUACtlRRRerbZZTBiQF6qeOSAtVkd9", // Topic Pop
        "Foals" => "PLgIOsBXGzlt25YJmit3J7gIcfCYqFjpZU", // Topic Pop 
        "Pet Shop Boys" => "PLAkqjw1_WMamUQwSwMlF8hYtOFvjpLbno", // Topic Pop
        "Paolo Nutini " => "PLI9qt-hgfDJMU9Iq6v0tLCgA3nvQT7-sp", // Topic Pop
        "Chic" => "PL9iNjvH1MsR49jD9HDW63_1tPqrf8dgyG", // Topic Pop
        "Lily Allen" => "PL3CYai1XDg4BLGH2Bv1AwEKBlmbmg_rCe", // Topic Pop
        "Blondie" => "PLjxXP6W9lSlT_jxKUf5fZmggAmo_2Pkjo", // Topic Pop
        "Simple Minds" => "PL2QT-cDQgJmOv8L1dl8NSYzwQtyLacAnl", // Topic Pop
        "Sinéad O\'Connor" => "PLd5eitdW94b1MksjJVyChzp1dAeyHPWpv", // Topic Pop
        "Mogwai" => "PL4Z-LDuzeu_BNKM6g3YR1MBhQp-IUOgZT", // Topic Pop
        "James Vincent McMorrow" => "PLXaENCdnmEnaiNNYJL40d1g1Ohas9RS61", // Topic Pop
        "James Murphy" => "PLuUycumDuV3Vvct_fxk1GYHiC9PwPKYvQ", // Topic Pop
        "SBTRKT" => "PLHhmEqx6v1mdoolEcq7AUZYzKu35um6wI", // Topic Pop
        "St. Vincent" => "PLLMMrCOYukXMx7p1p3wy5QfNOzKr5q9E3", // Topic Pop
        "Bombay Bicycle Club" => "PLjCEZtJ3LzpqziQEiBjk8wFmjo5cwNU-E", // Topic Pop
        "London Grammar" => "PLfX9wE3pl0JCWjwWSHFTpdXNHGjANY-sN", // Topic Pop
        "The 1975" => "PLNzsUFXjBLPzFGjjT2S6tUoPh9P-PiRLo", // Topic Pop
        "Slowdive" => "PLdaR2kkwXcVDaQcfQ2lpM8itr57tNOewm", // Topic Pop
        // "WILD BEASTS" => "", // Topic Pop
        "Metronomy" => "PLoiZCw85YuyBa0vudInmF5t3PO7JCn9QD", // Topic Pop
        // "KELIS" => "", // Topic Pop
        "Hozier" => "PLyjv-N5lxdiSwE2D4Zuy7bSr9ZTGdP6ro", // Topic Pop
        "The Strypes" => "PLhJgOb6g4GFmmcNmVpotMc5CgY6AKyLAt", // Topic Pop
        // "LAURA MVULA" => "", // Topic Pop
        // "DUKE DUMONT " => "", // Topic Pop
        // "THE STRANGLERS" => "", // Topic Pop
        "Flume" => "PL7S68UZm3-s4sWmziKMGked6aM8G78wsc", // Topic Pop
        // "THE BLADES" => "", // Topic Pop
        // "NENEH CHERRY" => "", // Topic Pop
        // "HERCULES" => "", // Topic Pop
        // "LOVE AFFAIR" => "", // Topic Pop
        // "ANNIE MAC " => "", // Topic Pop
        "Ham SandwicH" => "PL3FtvOPT7yIIN0ypU_o8OkPwozhl5bH1i", // Topic Pop
        // "CLEAN BANDIT" => "", // Topic Pop
        // "OMAR SOULEYMAN" => "", // Topic Pop
        // "THE WAILERS " => "", // Topic Pop
        // "THE HORRORS" => "", // Topic Pop
        "Le Galaxie" => "PLBUg5er7n1-03BGrZI2Cjl591h651_rU3" // Topic Pop
        // "TEMPLES" => "", // Topic Pop
        // "BP FALLON" => "", // Topic Pop
        // "THE GHOST WOLVES" => "", // Topic Pop
        // "SOHN " => "", // Topic Pop
        // "WHITE DENIM" => "", // Topic Pop
        // "TWIN SHADOW" => "", // Topic Pop
        // "JUNGLE" => "", // Topic Pop
        // "FKA TWIGS" => "", // Topic Pop
        // "BICEP" => "", // Topic Pop
        // "KAYTRANADA" => "", // Topic Pop
        // "SAMPHA (DJ SET)" => "", // Topic Pop
        // "SHIT ROBOT " => "", // Topic Pop
        // "KRYSTAL KLEAR" => "", // Topic Pop
        // "JOHN WIZARDS" => "", // Topic Pop
        // "WALKING ON CARS" => "", // Topic Pop
        // "NICK MULVEY" => "", // Topic Pop
        // "CATHY DAVEY" => "", // Topic Pop
        // "STEPHEN MALKMUS" => "", // Topic Pop
        // "THE JICKS" => "", // Topic Pop
        // "JENNY LEWIS" => "", // Topic Pop
        // "ASGEIR" => "", // Topic Pop
        // "WOLF ALICE " => "", // Topic Pop
        // "DRENGE" => "", // Topic Pop
        // "THE ORWELLS" => "", // Topic Pop
        // "UNKNOWN MORTAL ORCHESTRA" => "", // Topic Pop
        // "THE DISTRICTS" => "", // Topic Pop
        // "GLASS ANIMALS" => "", // Topic Pop
        // "SEINABO SEY" => "", // Topic Pop
        // "VAULTS " => "", // Topic Pop
        )
    )
);

?>