<?php
$names = array(
    "Electricpicnic" => "Electric Picnic",
    "Forbiddenfruit" => "Forbidden Fruit",
    "Trinityball" => "Trinity Ball",
    "Groovinthemoo" => "Groovin' The Moo",
    "Splendourinthegrass" => "Splendour In The Grass"
);

$noimages = array("longitude15", "groovinthemoo15", "latitude14", "electricpicnic14", "electricpicnic15", "splendourinthegrass15");

$festivals = array(
    "indiependence15" => array (
        1 => array (
            "Kodaline",
            "Basement Jaxx",
            "The Dandy Warhols",
            "Ash",
            "Jack Savoretti",
            "Mark Lanegan Band",
            "Ham Sandwich",
            "Embrace",
            "Jape",
            "Admiral Fallow",
            "The Original Rudeboys",
            "Spoken Word",
            "Daithí",
            "Grant Nicholas",
            "Krafty Kuts",
            "R.s.a.g",
            "The Young Folk",
            "Foy Vance",
            "Turbowolf",
            "Fish Go Deep",
            "Roisin O",
            "Hermitage Green",
            "The Academic",
            "All Tvvins",
            "Colm K",
            "KC",
            "Canci",
            "Kelly Anne Byrne",
            "Get Down Edits",
            "Eddie Kay",
            "Mother",
            "Culture Vultures",
            "Voxx",
            "The Would Be’s",
            "And Nun Came Back",
            "Maud in Cahoots",
            "Otherkin",
            "Columbia Mills",
            "Bridges",
            "Bribry",
            "Discopunks",
            "Slow Motion Heroes",
            "Phillip Henry and Hannah Martin",
            "The Vincents",
            "The Whereabouts",
            "State Lights",
            "Eaves",
            "Chris Haze",
            "Comedy",
            "Mkai",
            "Axis of",
            "Dolomite Minor",
            "Cry Monster Cry",
            "All the Luck in the World",
            "Half of Me",
            "Bel Canto Choir",
            "The Klares",
            "Stomptown Brass",
            "Amazing Apples",
            "Crow Black Chicken",
            "Elastic Sleep",
            "The North Sea",
            "The Flaws",
            "Wyvern Lingo",
            "Little Hours",
            "Orla Gartland",
            "Mindriot"
        )
    ),
    "forbiddenfruit14" => array(
        1 => array(
            "The Flaming Lips",
            "Bell X1",
            "Flying Lotus",
            "Fuck Buttons",
            "Nils Frahm",
            "Thundercat",
            "Captain Murphy",
            "Young Knives",
            "Kid Karate",
            "To Kill A King",
            "Vann Music",
            "2ManyDJs",
            "Soulwax",
            "Wild Beasts",
            "Warpaint",
            "Totally Enormous Extinct Dinosaurs",
            "Public Enemy",
            "Little Dragon",
            "Gold Panda",
            "Klangkarussell",
            "The Range",
            "Brian Deady"
        )
    ),
    "latitude14" => array (
        1 => array(
            "Two Door Cinema Club",
            "Editors",
            "Crystal Fighters",
            "Kelis",
            "Billy Bragg",
            "Damon Albarn",
            "Bombay Bicycle Club",
            "First Aid Kit",
            "The Afghan Whigs",
            "Booker T. Jones",
            "Tinariwen",
            "The Black Keys",
            "Tame Impala",
            "HAIM",
            "Phosphorescent",

            //BBC Radio 6 Music Stage
            "Asgeir Trausti",
            "Augustines",
            "Mogwai",
            "Slowdive",
            "Anna Calvi",
            "Goat",
            "Temples",
            "SOHN",
            "Hozier",
            "Röyksopp",
            "James Vincent McMorrow",
            "Daryl Hall and John Oates",
            "Jungle",
            "Conor Oberst",
            "Agnes Obel",
            "Damien Jurado",
            "Lykke Li",
            "Clean Bandit",
            "The War On Drugs",
            "Parquet Courts",
            "George Ezra",
            "Valerie June",

            //The Lake Stage
            "Luke Sital-Singh",
            "Chrissie Hynde",
            "Paul Heaton & Jacqui Abbott",
            "The Jayhawks",
            "Bondax",
            "Cate Le Bon",
            "Catfish & The Bottlemen",
            "Childhood",
            "Circa Waves",
            "D.D Dumbo",
            "Elli Ingram",
            "Gengahr",
            "Moko",
            "Norma Jean Martine",
            "Oliver Wilde",
            "Only Real",
            "Slaves",
            "Soak",
            "Spring King",
            "Sumie",
            "The Bohicas",
            "Womans Hour",

            //The i Arena
            "Cass McCombs", 
            "Dawes", 
            "Eagulls", 
            "East India Youth", 
            "Future Islands", 
            "Hiss Golden Messenger", 
            "James Holden", 
            "John Wizards", 
            "Josephine Foster", 
            "Julia Holter", 
            "Koreless", 
            "Kwabs", 
            "Marika Hackman", 
            "Mighty Oaks", 
            "MNEK", 
            "Nils Frahm", 
            "Rhodes", 
            "Ry X", 
            "Son Lux", 
            "Syd Arthur", 
            "Teen", 
            "The Acid", 
            "Tom Vek", 
            "Tycho", 
            "Vaults", 
            "Young Fathers", 
            //The Alcove
            "Ady Suleiman", 
            "Danni Nicholls", 
            "Elliphant", 
            "Emilie Nicholas", 
            "Glass Animals", 
            "Milky Chance",
            "Solomon Grey"
        )
    ),
    "life14" => array (
        1 => array(
            "Groove Armada",
            "Four Tet",
            "Jamie xx",
            "LFO",
            "Maya Jane Coles",
            "Joy Orbison",
            "Karenn",
            "Hot Since 82",
            "Nina Kraviz",
            "Dixon",
            "Ben Klock",
            "Dj Koze",
            "Tensnake",
            "Rødhåd",
            "Nathan Fake",
            "Ben Pearce",
            "Dusky",
            "Mala",
            "Waze & Odyssey",
            "Intergalactic Gary",
            "Maurice Fulton",
            "Ejeca",
            "New Jackson",
            "Avalon",
            "Sensient",
            "Kormac’s Big Band",
            "EVP",
            "Parasense",
            "Egorythmia",
            "Sunil Sharpe",
            "Frank B",
            "Lumigraph",
            "Barry Redsetta",
            "Nathan Jones",
            "Slowburn",
            "Jonas Rathsman",
            "Danny Wang",
            "R.S.A.G.",
            "S.P.Y.",
            "Raglans",
            "Lasertom",
            "Hot Sprockets",
            "Commodo",
            "Gantz",
            "Dublin Afrobeat Ensemble",
            "Sam Binga",
            "DJ Storm",
            "Harry Wolfman",
            "Real Connoisseur",
            "UnknwN",
            "Jacques Renault",
            "Mark Wells",
            "TCTS",
            "Lane 8",
            "Low Steppa",
            "Meltybrains",
            "Booka Brass Band",
            "Morro 16",
            "Lunar Disko",
            "Apartment Records",
            "Animal Picnic"
        )
    ),
    "trinityball14" => array(
        1 => array (
            "Example",
            "Miles Kane",
            "2ManyDJs",
            "Soulwax",
            "Duke Dumont",
            "Le Galaxie",
            "Nina Nesbitt",
            "Original Rudeboys",
            "Totally Enormous Extinct Dinosaurs",
            "Ben Pearce",
            "Wilkinson",
            "Chlöe Howl",
            "Laura Welsh",
            "Saint Raymond",
            "Godfathers"
        )
    ),
    "electricpicnic14" => array(
        1 => array (
            "Portishead",
            "Outkast",
            "Beck ",
            "Foals",
            "Pet Shop Boys",
            "Paolo Nutini ",
            "Chic",
            "Lily Allen",
            "Blondie",
            "Simple Minds",
            "Sinéad O'Connor",
            "Mogwai",
            "James Vincent McMorrow",
            "James Murphy",
            "SBTRKT",
            "St. Vincent",
            "Bombay Bicycle Club",
            "London Grammar",
            "The 1975",
            "Slowdive",
            "Wild Beasts",
            "Metronomy",
            "Kelis",
            "Hozier",
            "The Strypes",
            "Laura Mvula",
            "Duke Dumont",
            "The Stranglers",
            "Flume",
            "The Blades",
            "Neneh Cherry",
            "Hercules",
            "Love Affair",
            "Annie Mac",
            "Ham SandwicH",
            "Clean Bandit",
            "Omar Souleyman",
            "The Wailers ",
            "The Horrors",
            "Le Galaxie",
            "Temples",
            "Bp Fallon",
            "The Ghost Wolves",
            "Sohn ",
            "White Denim",
            "Twin Shadow",
            "Jungle",
            "Fka Twigs",
            "Bicep",
            "Kaytranada",
            "Sampha",
            "Shit Robot ",
            "Krystal Klear",
            "John Wizards",
            "Walking On Cars",
            "Nick Mulvey",
            "Cathy Davey",
            "Stephen Malkmus",
            "The Jicks",
            "Jenny Lewis",
            "Asgeir",
            "Wolf Alice ",
            "Drenge",
            "The Orwells",
            "Unknown Mortal Orchestra",
            "The Districts",
            "Glass Animals",
            "Seinabo Sey",
            "Vaults"
        )
    ),
    "electricpicnic15" => array(
        1 => array (
           "2 Unlimited",
           "5th Element",
           "A Sense of Place",
           "A.Skillz",
           "Abandoman",
           "Adam Hills",
           "After The Ibis",
           "Alvvays",
           "Ambience Affair",
           "Amnesty Hour: My Body My Rights",
           "Amy Quirke",
           "An Cabaret Craiceáilte",
           "Ana Gog",
           "Andrew Stanley",
           "Anthony Collins",
           "Aquilo",
           "Arubdub",
           "August Wells",
           "Barry Murphy",
           "Battles",
           "Beached Whales",
           "Bee-Loud Glade",
           "BeeMickSee",
           "Belle and Sebastian",
           "Ben Khan",
           "Benefit DJs",
           "Benjamin Clementine",
           "Blur",
           "Booka Brass Band",
           "Boss Level Series",
           "Boss Sound Manifesto",
           "Boys and Girls",
           "Braintheft",
           "Brian Deady",
           "Bridget Healy",
           "Bronagh Gallagher",
           "Brother Culture",
           "Bry",
           "Buckshot Amber",
           "Buffalo Sunn",
           "Chvrches",
           "Cian Finn",
           "Ciaran O",
           "Circa Waves",
           "CLG BEO!",
           "Clu",
           "Cristobal & The Sea",
           "Damsel",
           "Dan Taliras",
           "Danette Milne",
           "Daniel Sloss",
           "Danny Ryan",
           "Darragh J Glennon",
           "Dave Peyton",
           "Dave Treacy",
           "David J",
           "David McSavage",
           "David O'Doherty",
           "Dawes",
           "Deetrich",
           "Deidre O'Kane",
           "Dermot Kennedy",
           "Des Bishop",
           "Despacio",
           "Diana Dodog",
           "DJ Floydacide",
           "DJ Mek",
           "DJ Neil Flynn",
           "DJ OZ",
           "DJ Rico",
           "Django Django",
           "Dublin Gospel Choir",
           "Dublin Old School",
           "Dubtrash",
           "Duende Dogs",
           "East India Youth",
           "Ed Hick",
           "Edisons",
           "Edwin Sammon",
           "El Grey",
           "Elektrobank",
           "Elephant",
           "Fat White Family",
           "Fi",
           "Fickle Friends",
           "Fight Like Apes",
           "FKA twigs",
           "Florence + The Machine",
           "Foil Arms and Hog",
           "Food Fight",
           "Future Islands",
           "Gavin Glass",
           "Gavin James",
           "Gearoid Farrelly",
           "Gearoid Lynch",
           "George Ezra",
           "George Fitzgerald",
           "Getting Involved",
           "Ghostboy",
           "Gillian Nelis",
           "Gin N Juice",
           "Giotto",
           "Girl Band",
           "Girlpool",
           "Giro",
           "Glimmermen",
           "Good Man Sheila",
           "Grace Jones",
           "Graham Sweeney",
           "Grainne McKeever",
           "Grand",
           "Guerilla Aerial",
           "Hail The Ghost",
           "HamsandwicH",
           "Hands On!",
           "Hare Squead",
           "Haüer",
           "Hayes and Leslie",
           "Heartless Bastards",
           "Hector Feadán Rua",
           "Here We Go Magic",
           "Heroes In Hiding",
           "High Hopes Choir",
           "Hinds",
           "Hip Hop: Olwyn Lyons",
           "Ho99o9",
           "Homebrew",
           "Honne",
           "Hot Chip",
           "House of Yoga",
           "Hundred Waters",
           "I'm Your Vinly",
           "Iarla",
           "Idjut Boys",
           "Ignite",
           "Imbolg",
           "Imen McDonnell",
           "Imlé",
           "Inda Minyaaz",
           "Innocent and Monday",
           "Interpol",
           "Interskalactic",
           "Irie Live",
           "Iron Mountain",
           "Ivan Varian",
           "Jack Garratt",
           "Jackmaster",
           "Jahmonk",
           "Jape",
           "Joey Negro",
           "Johan van de Merwe",
           "John McKenna",
           "John Wilson",
           "Jon Hopkins",
           "Jonathan McCrea",
           "Joni",
           "JP McMahon",
           "Julio Bashmore",
           "Jupe",
           "Jurassic 5",
           "Kevin Thornton",
           "Kid Karate",
           "King Kong Company",
           "Kobina",
           "Kokiri",
           "Krystal Klear",
           "Kwabs",
           "Kwamie Liv",
           "Kwanghi Chan",
           "LA Priest",
           "Lambdancer",
           "Låpsley",
           "Le Boom",
           "Le Galaxie",
           "Legend",
           "LemonCello",
           "Leper and Chip",
           "Lerosa",
           "Leslie Williams",
           "Let Music Be Your Food",
           "Leviathan Political Cabaret",
           "Lily-Ramirez Foran",
           "Lingo",
           "Lionpaw",
           "Lisa O'Neill",
           "Little Hours",
           "Lorcan Rynne",
           "Low",
           "Lunar Disko",
           "Mac DeMarco",
           "Mad Dog Mcrea",
           "Madu",
           "Mahalia",
           "Mal Webb",
           "Manden Express",
           "Manic Street Precahers",
           "Mano le Tough",
           "Marc O'Reilly",
           "Marika Hackman",
           "Mark McCabe",
           "Mark Moriarty",
           "Mark Nelson",
           "Martin Shanahan",
           "Mary Ryan",
           "Maud In Cahoots",
           "Maurice Fulton",
           "MC Rungus",
           "Megacone",
           "Mei Chinn",
           "Meltybrains?",
           "Metz",
           "Michael Quinn",
           "Mick Donnellen",
           "Mick Flannery",
           "Milis",
           "Miriam Atkins",
           "Miriam Donohue",
           "Miss Scotty",
           "MK",
           "MKAI",
           "Molly Sterling",
           "Mongoose",
           "Mongrel State",
           "Monster Monster",
           "Mother DJs",
           "Mother Mooch",
           "Mr UpFull",
           "MS MR",
           "Mulljoy",
           "Murray Man",
           "Musici Ireland",
           "Mutefish",
           "My Fellow Sponges",
           "My Morning Jacket",
           "My Tribe Your Tribe",
           "Na Fadúdas – ceol beo",
           "Natalie Prass",
           "Natasha Czopor",
           "Nathan Johnson",
           "Neev Kennedy",
           "New Jackson",
           "O Emperor",
           "Ocho",
           "Oi Oi Soundsytem",
           "Oisín Davis",
           "Oki's Wagon",
           "Old Hannah",
           "Oliver Cole",
           "Oliver Nelson",
           "Onasis",
           "Opera Theatre Company",
           "Otherkin",
           "Out of Towners",
           "Paddy Dennehy & The Red Herring",
           "Panned",
           "Parquet Courts",
           "Pat Whelan",
           "Patrick McDonnell",
           "Paul Cadden",
           "Paul Flynn",
           "Paul Kalkbrenner",
           "Paul Woolford",
           "Peadar O Goill",
           "Pete Pamf",
           "Phil Cosby",
           "Pilgrim",
           "Plutonic Dust",
           "Poetry In The Park",
           "Pond",
           "Preachers Son",
           "Pressure Drop Soundsystem",
           "Printer Clips",
           "PTHM",
           "Punch Face Champions",
           "Puts Marie",
           "Quincey Fennelly",
           "R.S.A.G",
           "Race The Flux",
           "Raggaman Bob",
           "Raidió na Life",
           "Rayko",
           "Re:Raw",
           "Red Alert: Taboo",
           "Red Moon Bayonets",
           "Reggae Richie",
           "Replete",
           "Revelation Soundsystem",
           "Rhythm n Booze",
           "Richard and Duncan Blair",
           "RichardRichard",
           "Richie Hanlon",
           "Riddim Skribbler",
           "Ride",
           "Rís",
           "Risky Business",
           "Robocobra Quartet",
           "Róisín Murphy",
           "Róisín O",
           "Rosie Carney",
           "Rua",
           "Ruff Chuff",
           "Ryan Skelton's Together Disco",
           "Saint John The Gambler",
           "Saint Sister",
           "Sally McKenna",
           "Salon du Chat",
           "Salty Dog All Stars",
           "Sam Smith",
           "Saorla Trad Session",
           "Scene of the Rhyme",
           "Science Gallery Live Show",
           "Séamus Ruttledge",
           "Sean-Nós: Sibéal Davitt",
           "Seo Linn",
           "Seriaz Sounds",
           "Seskin Lane",
           "Shadow Boxer",
           "Sham Hanifa",
           "Shamir",
           "Shane Gillen",
           "Shannen Butler-Keane",
           "Shir Madness",
           "Shookrah",
           "Shura",
           "Silences",
           "Silent Interlude",
           "Silke Cropp",
           "Simi Crowns",
           "Sinéad White",
           "Skankin G",
           "Slap and Tickle",
           "Slick Normal",
           "Smidiríní",
           "SOAK",
           "Somerville",
           "Son Lux",
           "Sounds Alive",
           "Southpaw",
           "Tame Impala",
           "The Business",
           "The Cacks",
           "The Circle Sessions",
           "The Clameens",
           "The Clandestinos",
           "The Clark Family Project",
           "The Coronas",
           "The Cujo Family",
           "The Dingle Cookery School",
           "The Dodgy Few",
           "The Dub Doctor",
           "The Dublin Ukulele Collective",
           "The Dyatonics",
           "The Emerald Armada",
           "The Eskies",
           "The Eurotoques Young Chefs",
           "The Expert",
           "The Frank and Walters",
           "The Great Simones",
           "The Happy Pear",
           "The Hard Ground",
           "The Human Voice",
           "The Lost Brothers",
           "The Louisiana 6",
           "The Luna Boys",
           "The Man from Moogaga",
           "The Mighty Stef",
           "The New Breadwinners",
           "The New Social",
           "The Opposition",
           "The Pale",
           "The Pony Girls",
           "The Rattle Shakes",
           "The Redneck Manifesto",
           "The Reflex",
           "The Riptide Movement",
           "The River Fane",
           "The Roadhouse Doors",
           "The Rolling Tav Reveu",
           "The Rubberbandits",
           "The Service",
           "The Staves",
           "The Strypes",
           "The Tommy Moore Band",
           "The UK Bards",
           "The Urges",
           "The Vengaboys",
           "The War On Drugs",
           "The Whileaways",
           "The Winter Passing",
           "The Witch Trials",
           "Third Smoke",
           "This Is The Kit",
           "Thomston",
           "Todd Terry",
           "Tom Misch",
           "Tommy KD",
           "Tourist",
           "TR-One",
           "Trinitones",
           "Tuath",
           "Tucan",
           "Underworld",
           "Vaudou Game",
           "Veda",
           "Viet Cong",
           "Villagers",
           "Voxx",
           "Wade Murphy",
           "Waggamuffins",
           "We Cut Corners",
           "Weird Glitches",
           "White Boys",
           "Whitsey",
           "Wigwam DJs",
           "Will Softly",
           "William Barry",
           "Wino Boys",
           "Wolves of Youth",
           "World Bass Culture",
           "Worries Outernational",
           "Wyvern Lingo",
           "Yasiin Bey",
           "Young Wonder",
           "Yurodny",
           "Zaska",
           "Æ MAK"
        )
    ),
    "splendourinthegrass15" => array(
        1 => array (
            "Blur",
            "Mark Ronson",
            "Florence + The Machine",
            "Tale Impala",
            "Peking Duk",
            "Seekae",
            "Ryan Adams",
            "Flight Facilities",
            "Royal Blood",
            "Death Cab For Cutie",
            "Earl Sweatshirt",
            "Boy & Bear",
            "Porter Robinson",
            "The Dandy Warhols",
            "Xavier Rudd",
            "Azealia Banks",
            "the Rubens",
            "Jamie T",
            "Pond",
            "Spiritualized",
            "Alison Wonderland",
            "Thundamentals",
            "Best Coast",
            "Everything Everything",
            "San Cisco",
            "Ms Mr",
            "Jarryd James",
            "Purity Ring",
            "Meg Mac",
            "Allday",
            "Carmada",
            "The Grates",
            "The Smith Street Band",
            "Tkay Maidza",
            "Johnny Marr",
            "Last Dinosaurs",
            "Megan Washington",
            "the Vaccines",
            "#1 Dads",
            "the Church",
            "Kitty",
            "Daisy & Lewis",
            "The King Kahn & The BBQ show",
            "Alpine",
            "Catfish And The Bottlemen",
            "Paul Mac",
            "Dustin Tebbutt",
            "MØ",
            "Years & Years",
            "Jenny Lewis",
            "CW Stoneking",
            "Seekae",
            "George Maple",
            "Elliphant",
            "Client Liaison",
            "Palma Violets",
            "Safia",
            "Hayden James",
            "Dune Rats",
            "Wolf Alice",
            "Cosmo's Midnight",
            "Marmozets",
            "Oh Mercy",
            "Mansionair",
            "The Districts",
            "Shlohmo",
            "Elizabeth Rose",
            "The Delta Riggs",
            "Circa Waves",
            "Nancy Whang",
            "Eves The Behaviour",
            "Urban Cone",
            "Art Of Sleeping",
            "Japanese Wallpaper",
            "Gengahr",
            "Bad/Dreems",
            "Ecca Vandal",
            "Holy Holy",
            "Vallis Alps",
            "UV Boi",
            "The Babe Rainbow",
            "Harts",
            "Generik",
            "Young Franco",
            "Mickey Kojak",
            "GL Benson",
            "Harvey Sutherland",
            "Total Giovanni DJs ",
            "Dugong Jr",
            "I'lls Akouo",
            "Noise In My head",
            "Joyride",
            "Post Percy",
            "Ara Koufax",
            "CC: Disco!",
            "Adi Toohey",
            "Set Mo",
            "Edd Fisher",
            "Mike Who",
            "Shantan Wantan Ichiban"
        )
    ),
    "forbiddenfruit15" => array(
        1 => array (
            "Fatboy Slim",
            "Nicolas Jaar",
            "Disciples",
            "DJ Deece",
            "Wu-Tang Clan",
            "Earl Sweatshirt",
            "Tensnake",
            "Floating Points",
            "Fatima & The Eglo Live Band",
            "Blooms",
            "Rusangano Family",
            "Rocstrong",
            "Mr Scruff",
            "Joey Bada$$",
            "Bakermat",
            "Damian Lazarus",
            "Jamie xx",
            "Kelela",
            "Booka Brass Band",
            "Colm K",
            "Ejeca",
            "Dan Stritch",
            "Kaily",
            "Richie Hawtin",
            "Maya Jane Coles",
            "Gorgon City",
            "Adam Beyer",
            "Hot Since 82",
            "Booka Shade",
            "Run the Jewels",
            "Dusky",
            "Cyril Hahn",
            "Whilk & Misky",
            "MC Melodee",
            "Matador",
            "Waze & Odyssey",
            "Trinity Orchestra",
            "Sleep Thieves",
            "Heroes In Hiding",
            "Will Kinsella",
            "Jack Dunne",
            "4Ward Grad",
            "Gavin Francis"
        )
    ),
    "longitude15" => array(
        1 => array (
            "Hozier",
            "The Vaccines",
            "SBTRKT",
            "Metronomy",
            "Todd Terje",
            "Little Dragon",
            "Catfish & The Bottlemen",
            "Young Fathers",
            "Ibeyi",
            "Nick Mulvey",
            "Benjamin Booker",
            "Wyvern Lingo",
            "Subplots",
            "Alt-J",
            "Caribou",
            "Jungle",
            "Glass Animals",
            "Years & Years",
            "Pusha T",
            "Hudson Mohawke",
            "Toro Y Moi",
            "Daphni",
            "Girl Band",
            "Slaves",
            "Petite Noir",
            "Gengahr",
            "The Bohicas",
            "Daithi",
            "Princess",
            "The Chemical Brothers",
            "James Blake",
            "Wild Beasts",
            "Everything Everything",
            "Danny Brown",
            "Kaytranada",
            "Jose Gonzalez",
            "Tove Lo",
            "Wolf Alice",
            "Raury",
            "Drenge",
            "Young Wonder",
            "The Districts"
        )
    ),
    
    "groovinthemoo15" => array(
        1 => array (
            'A$AP Ferg', 
            "Ball Park Music", 
            "Broods", 
            "Carmada", 
            "Charli XCX", 
            "The Delta Riggs", 
            "DMA's", 
            "Flight Facilities", 
            "Hermitude", 
            "Hilltop Hoods", 
            "Hot Dub Time Machine", 
            "Meg Mac", 
            "Northlane", 
            "One Day", 
            "Peace", 
            "Peaches", 
            "The Preatures ", 
            "RL Grime", 
            "San Cisco", 
            "Saskwatch", 
            "Sticky Fingers", 
            "Tkay Maidza", 
            "Wolfmother", 
            "You Me At Six"
        )
    )
);

?>
