<?php
$names = array(
    "Electricpicnic" => "Electric Picnic",
    "Forbiddenfruit" => "Forbidden Fruit",
    "Trinityball" => "Trinity Ball",
    "Splendourinthegrass" => "Splendour In The Grass"
);

$noimages = array("latitude14", "electricpicnic14", "electricpicnic15", "splendourinthegrass15");

$festivals = array(
    "forbiddenfruit14" => array(
        1 => array(
            "The Flaming Lips",
            "Bell X1",
            "Flying Lotus",
            "Fuck Buttons",
            "Nils Frahm",
            "Thundercat",
            "Captain Murphy",
            "Young Knives",
            "Kid Karate",
            "To Kill A King",
            "Vann Music",
            "2ManyDJs",
            "Soulwax",
            "Wild Beasts",
            "Warpaint",
            "Totally Enormous Extinct Dinosaurs",
            "Public Enemy",
            "Little Dragon",
            "Gold Panda",
            "Klangkarussell",
            "The Range",
            "Brian Deady"
        )
    ),
    "latitude14" => array (
        1 => array(
            "Two Door Cinema Club",
            "Editors",
            "Crystal Fighters",
            "Kelis",
            "Billy Bragg",
            "Damon Albarn",
            "Bombay Bicycle Club",
            "First Aid Kit",
            "The Afghan Whigs",
            "Booker T. Jones",
            "Tinariwen",
            "The Black Keys",
            "Tame Impala",
            "HAIM",
            "Phosphorescent",

            //BBC Radio 6 Music Stage
            "Asgeir Trausti",
            "Augustines",
            "Mogwai",
            "Slowdive",
            "Anna Calvi",
            "Goat",
            "Temples",
            "SOHN",
            "Hozier",
            "Röyksopp",
            "James Vincent McMorrow",
            "Daryl Hall and John Oates",
            "Jungle",
            "Conor Oberst",
            "Agnes Obel",
            "Damien Jurado",
            "Lykke Li",
            "Clean Bandit",
            "The War On Drugs",
            "Parquet Courts",
            "George Ezra",
            "Valerie June",

            //The Lake Stage
            "Luke Sital-Singh",
            "Chrissie Hynde",
            "Paul Heaton & Jacqui Abbott",
            "The Jayhawks",
            "Bondax",
            "Cate Le Bon",
            "Catfish & The Bottlemen",
            "Childhood",
            "Circa Waves",
            "D.D Dumbo",
            "Elli Ingram",
            "Gengahr",
            "Moko",
            "Norma Jean Martine",
            "Oliver Wilde",
            "Only Real",
            "Slaves",
            "Soak",
            "Spring King",
            "Sumie",
            "The Bohicas",
            "Womans Hour",

            //The i Arena
            "Cass McCombs", 
            "Dawes", 
            "Eagulls", 
            "East India Youth", 
            "Future Islands", 
            "Hiss Golden Messenger", 
            "James Holden", 
            "John Wizards", 
            "Josephine Foster", 
            "Julia Holter", 
            "Koreless", 
            "Kwabs", 
            "Marika Hackman", 
            "Mighty Oaks", 
            "MNEK", 
            "Nils Frahm", 
            "Rhodes", 
            "Ry X", 
            "Son Lux", 
            "Syd Arthur", 
            "Teen", 
            "The Acid", 
            "Tom Vek", 
            "Tycho", 
            "Vaults", 
            "Young Fathers", 
            //The Alcove
            "Ady Suleiman", 
            "Danni Nicholls", 
            "Elliphant", 
            "Emilie Nicholas", 
            "Glass Animals", 
            "Milky Chance",
            "Solomon Grey"
        )
    ),
    "life14" => array (
        1 => array(
            "Groove Armada",
            "Four Tet",
            "Jamie xx",
            "LFO",
            "Maya Jane Coles",
            "Joy Orbison",
            "Karenn",
            "Hot Since 82",
            "Nina Kraviz",
            "Dixon",
            "Ben Klock",
            "Dj Koze",
            "Tensnake",
            "Rødhåd",
            "Nathan Fake",
            "Ben Pearce",
            "Dusky",
            "Mala SMALL",
            "Waze & Odyssey",
            "Intergalactic Gary",
            "Maurice Fulton",
            "Ejeca",
            "New Jackson",
            "Avalon",
            "Sensient",
            "Kormac’s Big Band",
            "EVP",
            "Parasense",
            "Egorythmia",
            "Sunil Sharpe",
            "Frank B",
            "Lumigraph",
            "Barry Redsetta",
            "Nathan Jones",
            "Slowburn",
            "Jonas Rathsman",
            "Danny Wang",
            "R.S.A.G.",
            "S.P.Y.",
            "Raglans",
            "Lasertom",
            "Hot Sprockets",
            "Commodo",
            "Gantz",
            "Dublin Afrobeat Ensemble",
            "Sam Binga",
            "DJ Storm",
            "Harry Wolfman",
            "Real Connoisseur",
            "UnknwN",
            "Jacques Renault",
            "Mark Wells",
            "TCTS",
            "Lane 8",
            "Low Steppa",
            "Meltybrains",
            "Booka Brass Band",
            "Morro 16",
            "Lunar Disko",
            "Apartment Records",
            "Animal Picnic"
        )
    ),
    "trinityball14" => array(
        1 => array (
            "Example",
            "Miles Kane",
            "2ManyDJs",
            "Soulwax",
            "Duke Dumont",
            "Le Galaxie",
            "Nina Nesbitt",
            "Original Rudeboys",
            "Totally Enormous Extinct Dinosaurs",
            "Ben Pearce",
            "Wilkinson",
            "Chlöe Howl",
            "Laura Welsh",
            "Saint Raymond",
            "Godfathers"
        )
    ),
    "electricpicnic14" => array(
        1 => array (
            "Portishead",
            "Outkast",
            "Beck ",
            "Foals",
            "Pet Shop Boys",
            "Paolo Nutini ",
            "Chic",
            "Lily Allen",
            "Blondie",
            "Simple Minds",
            "Sinéad O'Connor",
            "Mogwai",
            "James Vincent McMorrow",
            "James Murphy",
            "SBTRKT",
            "St. Vincent",
            "Bombay Bicycle Club",
            "London Grammar",
            "The 1975",
            "Slowdive",
            "Wild Beasts",
            "Metronomy",
            "Kelis",
            "Hozier",
            "The Strypes",
            "Laura Mvula",
            "Duke Dumont",
            "The Stranglers",
            "Flume",
            "The Blades",
            "Neneh Cherry",
            "Hercules",
            "Love Affair",
            "Annie Mac",
            "Ham SandwicH",
            "Clean Bandit",
            "Omar Souleyman",
            "The Wailers ",
            "The Horrors",
            "Le Galaxie",
            "Temples",
            "Bp Fallon",
            "The Ghost Wolves",
            "Sohn ",
            "White Denim",
            "Twin Shadow",
            "Jungle",
            "Fka Twigs",
            "Bicep",
            "Kaytranada",
            "Sampha",
            "Shit Robot ",
            "Krystal Klear",
            "John Wizards",
            "Walking On Cars",
            "Nick Mulvey",
            "Cathy Davey",
            "Stephen Malkmus",
            "The Jicks",
            "Jenny Lewis",
            "Asgeir",
            "Wolf Alice ",
            "Drenge",
            "The Orwells",
            "Unknown Mortal Orchestra",
            "The Districts",
            "Glass Animals",
            "Seinabo Sey",
            "Vaults"
        )
    ),
    "electricpicnic15" => array(
        1 => array (
           "Alvvays",
           "Aquilo",
           "Battles",
           "Belle & Sebastian",
           "Ben Khan",
           "Chvrches",
           "Circa Waves",
           "Curtis Harding",
           "Django Django",
           "Fight the Bear",
           "Florence + The Machine",
           "Future Islands",
           "George Ezra",
           "Girl Band",
           "Hinds",
           "Hot Chip",
           "Jack Garratt",
           "Jessie Ware",
           "Jon Hopkins",
           "Jurassic 5",
           "Kwabs",
           "Lapsley",
           "Little May",
           "Low",
           "Manic Street Preachers",
           "Marika Hackman",
           "Metz",
           "My Morning Jacket",
           "Pond",
           "Ride",
           "Róisín Murphy",
           "Shura",
           "Tame Impala",
           "The War On Drugs",
           "Tourist",
           "Underworld",
           "Wyvern Lingo"
        )
    ),
    "splendourinthegrass15" => array(
        1 => array (
            "Blur",
            "Mark Ronson",
            "Florence + The Machine",
            "Tale Impala",
            "Peking Duk",
            "Seekae",
            "Ryan Adams",
            "Flight Facilities",
            "Royal Blood",
            "Death Cab For Cutie",
            "Earl Sweatshirt",
            "Boy & Bear",
            "Porter Robinson",
            "The Dandy Warhols",
            "Xavier Rudd",
            "Azealia Banks",
            "the Rubens",
            "Jamie T",
            "Pond",
            "Spiritualized",
            "Alison Wonderland",
            "Thundamentals",
            "Best Coast",
            "Everything Everything",
            "San Cisco",
            "Ms Mr",
            "Jarryd James",
            "Purity Ring",
            "Meg Mac",
            "Allday",
            "Carmada",
            "The Grates",
            "The Smith Street Band",
            "Tkay Maidza",
            "Johnny Marr",
            "Last Dinosaurs",
            "Megan Washington",
            "the Vaccines",
            "#1 Dads",
            "the Church",
            "Kitty",
            "Daisy & Lewis",
            "The King Kahn & The BBQ show",
            "Alpine",
            "Catfish And The Bottlemen",
            "Paul Mac",
            "Dustin Tebbutt",
            "MØ",
            "Years & Years",
            "Jenny Lewis",
            "CW Stoneking",
            "Seekae",
            "George Maple",
            "Elliphant",
            "Client Liaison",
            "Palma Violets",
            "Safia",
            "Hayden James",
            "Dune Rats",
            "Wolf Alice",
            "Cosmo's Midnight",
            "Marmozets",
            "Oh Mercy",
            "Mansionair",
            "The Districts",
            "Shlohmo",
            "Elizabeth Rose",
            "The Delta Riggs",
            "Circa Waves",
            "Nancy Whang",
            "Eves The Behaviour",
            "Urban Cone",
            "Art Of Sleeping",
            "Japanese Wallpaper",
            "Gengahr",
            "Bad/Dreems",
            "Ecca Vandal",
            "Holy Holy",
            "Vallis Alps",
            "UV Boi",
            "The Babe Rainbow",
            "Harts",
            "Generik",
            "Young Franco",
            "Mickey Kojak",
            "GL Benson",
            "Harvey Sutherland",
            "Total Giovanni DJs ",
            "Dugong Jr",
            "I'lls Akouo",
            "Noise In My head",
            "Joyride",
            "Post Percy",
            "Ara Koufax",
            "CC: Disco!",
            "Adi Toohey",
            "Set Mo",
            "Edd Fisher",
            "Mike Who",
            "Shantan Wantan Ichiban"
        )
    )
);

?>
